services:
  postgres-service:
    image: postgres:15-alpine
    container_name: postgres-service
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: anticorruption-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres-service
    # Mount the local config.yaml into the container so we can change it on the fly.
    volumes:
      - ./example.yaml:/app/config.yaml

volumes:
  postgres_data:
