api:
  image:
    repository: localhost:5000/anticorruption-api
    tag: "latest"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  configMap:
    # This is the "Config-as-Code" mapping configuration for the API.
    # The API will load this content into a ConfigMap that is mounted into the container.
    mapping: |-
      mappings:
        - api_endpoint: /users
          query: "SELECT id, username, email, created_at FROM users;"
          columns:
            id: user_id
            username: name
            email: email_address
            created_at: registration_date
        - api_endpoint: /data
          query: "SELECT id, data_value, updated_at FROM data_table;"
          columns:
            id: data_id
            data_value: value
            updated_at: last_update
        - api_endpoint: /orders
          query: "SELECT order_id, customer_id, total, order_date FROM orders;"
          columns:
            order_id: id
            customer_id: customer
            total: amount
            order_date: date

postgres:
  image:
    repository: postgres
    tag: "15-alpine"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5432
  credentials:
    user: postgres
    password: password
    db: mydb