apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anti-corruption-app
  namespace: argocd
spec:
  project: default  # Change this if you have a specific project
  source:
    repoURL: 'git@github.com:saltcheese-honey/anti-corruption-layers.git'  # Use a valid Git URL or local file path
    targetRevision: main
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
